/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type { Settlement, SettlementInterface } from "../Settlement";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes",
        name: "orderUid",
        type: "bytes",
      },
      {
        internalType: "bool",
        name: "signed",
        type: "bool",
      },
    ],
    name: "setPreSignature",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class Settlement__factory {
  static readonly abi = _abi;
  static createInterface(): SettlementInterface {
    return new utils.Interface(_abi) as SettlementInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): Settlement {
    return new Contract(address, _abi, signerOrProvider) as Settlement;
  }
}
